In [1]:
import statsmodels.api as sm
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("General Linear Model Data.xlsx")
df.head(15)

Country Name  2017 Expen PPP   Unnamed: 2  \
0                 Angola      185.854034   185.854034   
1                Andorra     5237.241699  5237.241699   
2   United Arab Emirates     2468.549316  2468.549316   
3              Argentina     1916.504150  1916.504150   
4                Armenia     1001.069031  1001.069031   
5    Antigua and Barbuda     1070.769165  1070.769165   
6              Australia     4816.153809  4816.153809   
7                Austria     5617.396484  5617.396484   
8             Azerbaijan     1163.861938  1163.861938   
9                Burundi       59.188663    59.188663   
10               Belgium     5119.074707  5119.074707   
11                 Benin       84.650986    84.650986   
12          Burkina Faso      129.064270   129.064270   
13            Bangladesh       94.302017    94.302017   
14              Bulgaria     1689.687134  1689.687134   

    2017 Expen PPP(Rounded)    Case  Unnamed: 5  Unnamed: 6  Case(Neg)  
0                       186    2044        2044          -1      -2044  
1                      5237    1024        1024          -1      -1024  
2                      2469   65802       65802          -1     -65802  
3                      1917  320884      320884          -1    -320884  
4                      1001   42319       42319          -1     -42319  
5                      1071      94          94          -1        -94  
6                      4816   24417       24417          -1     -24417  
7                      5617   24431       24431          -1     -24431  
8                      1164   34759       34759          -1     -34759  
9                        59     422         422          -1       -422  
10                     5119   83769       83769          -1     -83769  
11                       85    2095        2095          -1      -2095  
12                      129    1297        1297          -1      -1297  
13                       94  287959      287959          -1    -287959  
14                     1690   14962       14962          -1     -14962

In [3]:
df

Country Name  2017 Expen PPP   Unnamed: 2  \
0                  Angola      185.854034   185.854034   
1                 Andorra     5237.241699  5237.241699   
2    United Arab Emirates     2468.549316  2468.549316   
3               Argentina     1916.504150  1916.504150   
4                 Armenia     1001.069031  1001.069031   
..                    ...             ...          ...   
167         Venezuela, RB      141.022202   141.022202   
168               Vietnam      375.643250   375.643250   
169          South Africa     1097.819214  1097.819214   
170                Zambia      180.270660   180.270660   
171              Zimbabwe      201.045456   201.045456   

     2017 Expen PPP(Rounded)    Case  Unnamed: 5  Unnamed: 6  Case(Neg)  
0                        186    2044        2044          -1      -2044  
1                       5237    1024        1024          -1      -1024  
2                       2469   65802       65802          -1     -65802  
3                       1917  320884      320884          -1    -320884  
4                       1001   42319       42319          -1     -42319  
..                       ...     ...         ...         ...        ...  
167                      141   36868       36868          -1     -36868  
168                      376    1007        1007          -1      -1007  
169                     1098  599940      599940          -1    -599940  
170                      180   10372       10372          -1     -10372  
171                      201    5745        5745          -1      -5745  

[172 rows x 8 columns]

In [4]:
print(df['Country Name'])

0                    Angola
1                   Andorra
2      United Arab Emirates
3                 Argentina
4                   Armenia
               ...         
167           Venezuela, RB
168                 Vietnam
169            South Africa
170                  Zambia
171                Zimbabwe
Name: Country Name, Length: 172, dtype: object


In [5]:
print(df['Case'])

0        2044
1        1024
2       65802
3      320884
4       42319
        ...  
167     36868
168      1007
169    599940
170     10372
171      5745
Name: Case, Length: 172, dtype: int64


In [6]:
df['2017 Expen PPP']

0       185.854034
1      5237.241699
2      2468.549316
3      1916.504150
4      1001.069031
          ...     
167     141.022202
168     375.643250
169    1097.819214
170     180.270660
171     201.045456
Name: 2017 Expen PPP, Length: 172, dtype: float64

In [7]:
X = df['2017 Expen PPP']

In [8]:
y = df['Case']

In [9]:
X

0       185.854034
1      5237.241699
2      2468.549316
3      1916.504150
4      1001.069031
          ...     
167     141.022202
168     375.643250
169    1097.819214
170     180.270660
171     201.045456
Name: 2017 Expen PPP, Length: 172, dtype: float64

In [10]:
print(len(X))

172


In [11]:
X = np.array(df['2017 Expen PPP(Rounded)'])

In [12]:
X

array([  186,  5237,  2469,  1917,  1001,  1071,  4816,  5617,  1164,
          59,  5119,    85,   129,    94,  1690,  2265,  1756,  1172,
        1129,   481,   492,  1472,  1343,  1875,   290,  1044,    42,
        4929,  8217,  2229,   841,   176,   174,    37,   165,  1039,
         123,   357,  1262,  2486,  2430,  2753,  5923,   117,   657,
        5510,   986,   975,   959,   614,    59,  3469,  2153,    67,
        4255,   323,  5011,   500,  4338,   773,   147,    89,    56,
         123,   759,  2295,   721,   475,   405,   395,  1772,   146,
        1979,   368,   253,  5545,  1748,  4721,  3015,  3620,   543,
         757,  4563,   820,   158,   241,   238,  1442,  2980,  3797,
         178,  1185,   105,   662,   504,   266,  2133,  5956,  1682,
         438,  2991,   477,    85,  1507,  1036,   927,    84,  3943,
         288,   518,    62,   170,  1278,   115,  1139,   895,    79,
         221,   506,  5513,  6519,   150,  3768,  1591,   161,  1795,
         681,   372,

In [21]:
################
X = sm.add_constant(X, prepend=False)

In [22]:
X

array([[1.8600e+02, 1.0000e+00],
       [5.2370e+03, 1.0000e+00],
       [2.4690e+03, 1.0000e+00],
       [1.9170e+03, 1.0000e+00],
       [1.0010e+03, 1.0000e+00],
       [1.0710e+03, 1.0000e+00],
       [4.8160e+03, 1.0000e+00],
       [5.6170e+03, 1.0000e+00],
       [1.1640e+03, 1.0000e+00],
       [5.9000e+01, 1.0000e+00],
       [5.1190e+03, 1.0000e+00],
       [8.5000e+01, 1.0000e+00],
       [1.2900e+02, 1.0000e+00],
       [9.4000e+01, 1.0000e+00],
       [1.6900e+03, 1.0000e+00],
       [2.2650e+03, 1.0000e+00],
       [1.7560e+03, 1.0000e+00],
       [1.1720e+03, 1.0000e+00],
       [1.1290e+03, 1.0000e+00],
       [4.8100e+02, 1.0000e+00],
       [4.9200e+02, 1.0000e+00],
       [1.4720e+03, 1.0000e+00],
       [1.3430e+03, 1.0000e+00],
       [1.8750e+03, 1.0000e+00],
       [2.9000e+02, 1.0000e+00],
       [1.0440e+03, 1.0000e+00],
       [4.2000e+01, 1.0000e+00],
       [4.9290e+03, 1.0000e+00],
       [8.2170e+03, 1.0000e+00],
       [2.2290e+03, 1.0000e+00],
       [8.

In [15]:
y = np.array(df['Case'])

In [16]:
y

array([   2044,    1024,   65802,  320884,   42319,      94,   24417,
         24431,   34759,     422,   83769,    2095,    1297,  287959,
         14962,   48303,    1610,   17029,   69950,     605,  105050,
       3456652,     156,     143,     150,    1308,    4679,  125625,
         39026,  391849,   89551,   17989,   18762,    9757,    3850,
        502178,     417,    3368,   31075,    3565,    1395,   21045,
        231292,    5374,      18,   16453,   89010,   40258,  105508,
         97025,     306,  377906,    2227,   35836,    7842,      28,
        256534,    8319,  324196,    1370,   43260,    8876,    2401,
          2149,    4892,    7934,      24,   65983,     846,   52298,
          7329,    7997,    5046,  147211, 2836925,   27676,  352558,
          2040,   99599,  256118,    1192,    1498,   59895,  103815,
         31441,   42507,     273,      17,   16346,   78767,      22,
         10952,    1284,      26,    2918,     996,    2528,    7637,
          1327,   47

In [17]:
# Ordinary least square method.
mod = sm.OLS(y, X)

In [18]:
res = mod.fit()

In [19]:
print(res.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.081
Model:                            OLS   Adj. R-squared:                  0.075
Method:                 Least Squares   F-statistic:                     14.95
Date:                Fri, 21 Aug 2020   Prob (F-statistic):           0.000157
Time:                        13:29:31   Log-Likelihood:                -2509.7
No. Observations:                 172   AIC:                             5023.
Df Residuals:                     170   BIC:                             5030.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            86.0046     22.244      3.866      0.0